Repository IBM-Cloud/terraform-provider-ibm, pull requests merged in 2025-04, with the labels that each got.

#6079 Secrets Manager - allow configuring IAM endpoint with endpoints file
  ibm/service/secretsmanager/data_source_ibm_sm_arbitrary_secret_metadata.go
  ibm/service/secretsmanager/data_source_ibm_sm_configurations.go
  ibm/service/secretsmanager/data_source_ibm_sm_en_registration.go
  ibm/service/secretsmanager/data_source_ibm_sm_iam_credentials_configuration.go
  ibm/service/secretsmanager/data_source_ibm_sm_iam_credentials_secret_metadata.go
  ibm/service/secretsmanager/data_source_ibm_sm_imported_certificate_metadata.go
  ibm/service/secretsmanager/data_source_ibm_sm_kv_secret_metadata.go
  ibm/service/secretsmanager/data_source_ibm_sm_private_certificate_configuration_intermediate_ca.go
  ibm/service/secretsmanager/data_source_ibm_sm_private_certificate_configuration_root_ca.go
  ibm/service/secretsmanager/data_source_ibm_sm_private_certificate_configuration_template.go
  ibm/service/secretsmanager/data_source_ibm_sm_private_certificate_metadata.go
  ibm/service/secretsmanager/data_source_ibm_sm_public_certificate_configuration_ca_lets_encrypt.go
  ibm/service/secretsmanager/data_source_ibm_sm_public_certificate_configuration_dns_cis.go
  ibm/service/secretsmanager/data_source_ibm_sm_public_certificate_configuration_dns_classic_infrastructure.go
  ibm/service/secretsmanager/data_source_ibm_sm_public_certificate_metadata.go
  ibm/service/secretsmanager/data_source_ibm_sm_secret_group.go
  ibm/service/secretsmanager/data_source_ibm_sm_secret_groups.go
  ibm/service/secretsmanager/data_source_ibm_sm_secrets.go
  ibm/service/secretsmanager/data_source_ibm_sm_service_credentials_secret_metadata.go
  ibm/service/secretsmanager/data_source_ibm_sm_username_password_secret_metadata.go
  ibm/service/secretsmanager/resource_ibm_sm_arbitrary_secret.go
  ibm/service/secretsmanager/resource_ibm_sm_en_registration.go
  ibm/service/secretsmanager/resource_ibm_sm_iam_credentials_configuration.go
  ibm/service/secretsmanager/resource_ibm_sm_iam_credentials_secret.go
  ibm/service/secretsmanager/resource_ibm_sm_imported_certificate.go
  ibm/service/secretsmanager/resource_ibm_sm_kv_secret.go
  ibm/service/secretsmanager/resource_ibm_sm_private_certificate.go
  ibm/service/secretsmanager/resource_ibm_sm_private_certificate_configuration_action_set_signed.go
  ibm/service/secretsmanager/resource_ibm_sm_private_certificate_configuration_action_sign_csr.go
  ibm/service/secretsmanager/resource_ibm_sm_private_certificate_configuration_intermediate_ca.go
  ibm/service/secretsmanager/resource_ibm_sm_private_certificate_configuration_root_ca.go
  ibm/service/secretsmanager/resource_ibm_sm_private_certificate_configuration_template.go
  ibm/service/secretsmanager/resource_ibm_sm_public_certificate.go
  ibm/service/secretsmanager/resource_ibm_sm_public_certificate_action_validate_manual_dns.go
  ibm/service/secretsmanager/resource_ibm_sm_public_certificate_configuration_ca_lets_encrypt.go
  ibm/service/secretsmanager/resource_ibm_sm_public_certificate_configuration_dns_cis.go
  ibm/service/secretsmanager/resource_ibm_sm_public_certificate_configuration_dns_classic_infrastructure.go
  ibm/service/secretsmanager/resource_ibm_sm_secret_group.go
  ibm/service/secretsmanager/resource_ibm_sm_service_credentials_secret.go
  ibm/service/secretsmanager/resource_ibm_sm_username_password_secret.go
  ibm/service/secretsmanager/utils.go
Labels: service/Secrets Manager

#6110 Remove deprecation note from pi_license_repository_capacity
  ibm/service/power/resource_ibm_pi_instance.go
  website/docs/r/pi_instance.html.markdown
Labels: service/Power Systems

#6097 Remove warnings from terraform spp and pg markdown files
  website/docs/d/pi_placement_group.html.markdown
  website/docs/d/pi_placement_groups.html.markdown
  website/docs/d/pi_shared_processor_pool.html.markdown
  website/docs/d/pi_shared_processor_pools.html.markdown
  website/docs/d/pi_spp_placement_group.html.markdown
  website/docs/d/pi_spp_placement_groups.html.markdown
  website/docs/r/pi_placement_group.html.markdown
  website/docs/r/pi_shared_processor_pool.html.markdown
  website/docs/r/pi_spp_placement_group.html.markdown
Labels: service/Power Systems

#6106 [Resource] Fix NSG Action Crashes
  ibm/service/power/resource_ibm_pi_network_security_group_action.go
  ibm/service/power/resource_ibm_pi_network_security_group_action_test.go
Labels: service/Power Systems

#6100 Remove warnings from terraform cloud connection and vsn markdown files
  website/docs/d/pi_cloud_connection.html.markdown
  website/docs/d/pi_cloud_connections.html.markdown
  website/docs/d/pi_cloud_instance.html.markdown
  website/docs/d/pi_virtual_serial_number.html.markdown
  website/docs/d/pi_virtual_serial_numbers.html.markdown
  website/docs/r/pi_cloud_connection.html.markdown
  website/docs/r/pi_cloud_connection_network_attach.html.markdown
  website/docs/r/pi_virtual_serial_number.html.markdown
Labels: service/Power Systems

#6099 Remove warnings from terraform dhcp and ssh-key markdown files
  website/docs/d/pi_dhcp.html.markdown
  website/docs/d/pi_dhcps.html.markdown
  website/docs/d/pi_key.html.markdown
  website/docs/d/pi_keys.html.markdown
  website/docs/r/pi_dhcp.html.markdown
  website/docs/r/pi_key.html.markdown
Labels: service/Power Systems

#6091 Remove warnings from terraform image markdown files
  website/docs/d/pi_catalog_images.html.markdown
  website/docs/d/pi_image.html.markdown
  website/docs/d/pi_images.html.markdown
  website/docs/r/pi_image.html.markdown
  website/docs/r/pi_image_export.html.markdown
Labels: service/Power Systems

#6090 Remove unused constants in the code
  ibm/service/power/ibm_pi_constants.go
Labels: service/Power Systems

#6092 Remove warnings from terraform volume markdown files
  website/docs/d/pi_volume.html.markdown
  website/docs/d/pi_volume_flash_copy_mappings_html.markdown
  website/docs/d/pi_volume_onboarding.html.markdown
  website/docs/d/pi_volume_onboardings.html.markdown
  website/docs/d/pi_volume_remote_copy_relationship.html.markdown
  website/docs/r/pi_volume.html.markdown
  website/docs/r/pi_volume_attach.html.markdown
  website/docs/r/pi_volume_clone.html.markdown
  website/docs/r/pi_volume_onboarding.html.markdown
Labels: service/Power Systems

#6093 Remove warnings from terraform network markdown files
  website/docs/d/pi_network.html.markdown
  website/docs/d/pi_network_address_groups.html.markdown
  website/docs/d/pi_network_peers.html.markdown
  website/docs/d/pi_network_port.html.markdown
  website/docs/d/pi_network_security_groups.html.markdown
  website/docs/d/pi_networks.html.markdown
  website/docs/d/pi_public_network.html.markdown
  website/docs/r/pi_network.html.markdown
  website/docs/r/pi_network_port_attach.html.markdown
  website/docs/r/pi_network_security_group_rule.html.markdown
Labels: service/Power Systems

#6095 Remove warnings from terraform instance markdown files
  website/docs/d/pi_instance.html.markdown
  website/docs/d/pi_instance_ip.html.markdown
  website/docs/d/pi_instance_snapshot.html.markdown
  website/docs/d/pi_instance_snapshots.html.markdown
  website/docs/d/pi_instance_volumes.html.markdown
  website/docs/d/pi_instances.html.markdown
  website/docs/r/pi_capture.html.markdown
  website/docs/r/pi_instance.html.markdown
  website/docs/r/pi_instance_action.html.markdown
  website/docs/r/pi_instance_snapshot.html.markdown
Labels: service/Power Systems

#6096 Remove warnings from terraform host and host-group markdown files
  website/docs/d/pi_host.html.markdown
  website/docs/d/pi_host_group.html.markdown
  website/docs/r/pi_host.html.markdown
  website/docs/r/pi_host_group.html.markdown
Labels: service/Power Systems

#6098 Remove warnings from terraform datacenter and workspace markdown files
  website/docs/d/pi_datacenter.html.markdown
  website/docs/d/pi_datacenters.html.markdown
  website/docs/d/pi_workspace.html.markdown
  website/docs/d/pi_workspaces.html.markdown
  website/docs/r/pi_workspace.html.markdown
Labels: service/Power Systems

#6101 Remove warning from the remainder of the docs update
  website/docs/d/pi_console_languages.html.markdown
  website/docs/d/pi_disaster_recovery_location.html.markdown
  website/docs/d/pi_disaster_recovery_locations.html.markdown
  website/docs/d/pi_sap_profile.html.markdown
  website/docs/d/pi_sap_profiles.html.markdown
  website/docs/d/pi_storage_pool_capacity.markdown
  website/docs/d/pi_storage_pools_capacity.markdown
  website/docs/d/pi_storage_type_capacity.markdown
  website/docs/d/pi_storage_types_capacity.markdown
  website/docs/d/pi_tenant.html.markdown
  website/docs/r/pi_snapshot.html.markdown
Labels: service/Power Systems

#6159 Fix warnings in pi data source and resources
  ibm/acctest/acctest.go
  ibm/service/power/data_source_ibm_pi_cloud_connection.go
  ibm/service/power/data_source_ibm_pi_cloud_connections.go
  ibm/service/power/data_source_ibm_pi_instance_volumes_test.go
  ibm/service/power/data_source_ibm_pi_sap_profile_test.go
  ibm/service/power/resource_ibm_pi_capture.go
  ibm/service/power/resource_ibm_pi_capture_test.go
  ibm/service/power/resource_ibm_pi_cloud_connection.go
  ibm/service/power/resource_ibm_pi_host.go
  ibm/service/power/resource_ibm_pi_image.go
  ibm/service/power/resource_ibm_pi_network.go
  ibm/service/power/resource_ibm_pi_placement_group_test.go
  ibm/service/power/resource_ibm_pi_spp_placement_group_test.go
Labels: service/Power Systems

#6166 [Datasource] Fix crash when vm has no volumes
  ibm/service/power/data_source_ibm_pi_instance_volumes.go
Labels: bug, service/Power Systems

#6168 [Datasource] Deprecate CRN attribute from ibm_pi_volume_snapshot(s)
  ibm/service/power/data_source_ibm_pi_volume_snapshot.go
  ibm/service/power/data_source_ibm_pi_volume_snapshots.go
  website/docs/d/pi_volume_snapshot.html.markdown
  website/docs/d/pi_volume_snapshots.html.markdown
Labels: service/Power Systems
